import { OrganizationSwitcher, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

import type { Metadata } from 'next'
import "@/styles/globals.css"
import { Inter as FontSans } from "next/font/google"

import { Analytics } from '@vercel/analytics/react';
import { AxiomWebVitals } from 'next-axiom';

import { Toaster } from "@/components/ui/toaster"

import { cn } from "@/lib/utils"
import { MainNav } from '@/components/main-nav';
import { Search } from '@/components/search';
import { ThemeModeToggle } from '@/components/theme-mode-toggle';
import { Providers } from './providers';
import { CommandMenu } from '@/components/shared/command-menu';
import SignInButton from '@/components/auth/sign-in-button';

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <Providers>
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <MainNav className="mx-6" />
              <div className="ml-auto flex items-center space-x-4">
                <ThemeModeToggle />
                <SignedIn>
                  <Search />
                  <OrganizationSwitcher />
                  <UserButton afterSignOutUrl="/" />
                </SignedIn>
                <SignedOut>
                  <SignInButton />
                </SignedOut>
              </div>
            </div>
          </div>
          <div className="flex-1 space-y-4 p-8 pt-6">
            {children}
          </div>

          <CommandMenu />
          <Toaster />
          <Analytics />
          <AxiomWebVitals />
        </Providers>
      </body>
    </html>
  )
}
